WhatToDo/WhatToDo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls', namespace='home')),
    path('user/', include('appuser.urls', namespace='user')),
]

WhatToDo/appuser/urls.py
from django.urls import path
from .views import RegisterView, CustomLoginView, CustomLogoutView


app_name = "user"


urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    # path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    # path('reset-password/', ResetPasswordView.as_view(), name='reset_password'),
]

WhatToDo/task/urls.py
from django.urls import path
from .views import IndexView, ProfileView, TaskCreateView, SubTasksView

app_name = 'home'


urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('create_task/', TaskCreateView.as_view(), name='create_task'),
    path('sube_tasks/<int:task_id>', SubTasksView.as_view(), name='subtasks'),
]

WhatToDo/appuser/models.py
from django.db import models
from django.contrib.auth.models import User


class AppUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    bio = models.TextField(blank=True, null=True) 
    profile_picture = models.ImageField(upload_to='profiles/', blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.user.username

WhatToDo/appuser/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import View
from appuser.models import AppUser


class RegisterView(View):
    def get(self, request):
        return render(request, 'sign-up.html')

    def post(self, request):
        username = request.POST.get('username', False)
        email = request.POST.get('email', False)
        password = request.POST.get('password', False)

        if not all([username, email, password]):

            if User.objects.filter(username=username).exists():
                messages.error(request, "نام کاربری قبلاً استفاده شده است!")
                return render(request, 'register.html')
            
            user = User.objects.create_user(username=username, email=email, password=password)
            appuser = AppUser.objects.create(user=user)
            appuser.save()
            user.save()
            messages.success(request, "ثبت‌نام موفق بود!")
            return redirect(reverse('user:login'))


class CustomLoginView(View):
    def get(self, request):
        if request.user and request.user.is_authenticated:
            print("user is logged in already")
            return redirect(reverse('home:index'))
        return render(request, 'sign-in.html')

    def post(self, request):
        username = request.POST.get('username', False) #  TODO: using email to login
        password = request.POST.get('password', False)
        
        print(username, password)
        
        if not all([username, password]):
            messages.error(request, "لطفاً همه‌ی فیلدها را پر کنید!")
            return render(request, 'sign-in.html')
        
        user = authenticate(request, username=username, password=password)
                
        if user:
            login(request, user)
            messages.success(request, "logged in successfully!")
            print("cannot og user in")
            return redirect(reverse('home:index'))
        else:
            print("cannot log user in")
            messages.error(request, "wrong credentials!")
            return render(request, 'sign-in.html')

class CustomLogoutView(View):
    def get(self, request):
        logout(request)
        messages.success(request, "شما با موفقیت خارج شدید!")
        return redirect(reverse('user:login'))


# class ChangePasswordView(View):
#     def get(self, request):
#         return render(request, 'change_password.html')

#     def post(self, request):
#         old_password = request.POST.get('old_password')
#         new_password = request.POST.get('new_password')
#         confirm_password = request.POST.get('confirm_password')

#         if not request.user.check_password(old_password):
#             messages.error(request, "رمز عبور فعلی اشتباه است!")
#             return render(request, 'appuser/change_password.html')

#         if new_password != confirm_password:
#             messages.error(request, "رمز عبور جدید و تأیید آن یکسان نیست!")
#             return render(request, 'appuser/change_password.html')
        
#         request.user.set_password(new_password)
#         request.user.save()
#         update_session_auth_hash(request, request.user)
#         messages.success(request, "رمز عبور با موفقیت تغییر کرد!")
#         return redirect('home')




# class ResetPasswordView(PasswordResetView):
#     template_name = 'appuser/reset_password.html'
#     email_template_name = 'appuser/reset_password_email.html'
#     success_url = reverse_lazy('login')

#     def form_valid(self, form):
#         messages.success(self.request, "اگر ایمیل شما در سیستم باشد، لینک تغییر رمز ارسال خواهد شد.")
#         return super().form_valid(form)

WhatToDo/appuser/templates/sign-in.html
<!--
=========================================================
* Material Dashboard 3 - v3.2.0
=========================================================

* Product Page: https://www.creative-tim.com/product/material-dashboard
* Copyright 2024 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->

{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <title>
    Material Dashboard 3 by Creative Tim
  </title>
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700,900" />
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" />
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static 'css/material-dashboard.css' %}" rel="stylesheet" />
</head>

<body class="bg-gray-200">
  <main class="main-content  mt-0">
    <div class="page-header align-items-start min-vh-100"
      style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-4 col-md-8 col-12 mx-auto">
            <div class="card z-index-0 fadeIn3 fadeInBottom">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-dark shadow-dark border-radius-lg py-3 pe-1">
                  <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Sign in</h4>
                  <div class="row mt-3">
                    <div class="col-2 text-center ms-auto">
                      <a class="btn btn-link px-3" href="javascript:;">
                        <i class="fa fa-facebook text-white text-lg"></i>
                      </a>
                    </div>
                    <div class="col-2 text-center px-1">
                      <a class="btn btn-link px-3" href="javascript:;">
                        <i class="fa fa-github text-white text-lg"></i>
                      </a>
                    </div>
                    <div class="col-2 text-center me-auto">
                      <a class="btn btn-link px-3" href="javascript:;">
                        <i class="fa fa-google text-white text-lg"></i>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-body">
                <form role="form" class="text-start" method="post" action="{% url 'user:login' %}">
                  {% csrf_token %}
                  <div class="input-group input-group-outline my-3">
                    <!-- <label class="form-label">Email</label>
                    <input type="email" class="form-control" name="email"> -->
                    <label class="form-label">Username</label>
                    <input type="text" class="form-control" name="username">
                  </div>
                  <div class="input-group input-group-outline mb-3">
                    <label class="form-label">Password</label>
                    <input type="password" class="form-control" name="password">
                  </div>
                  <div class="form-check form-switch d-flex align-items-center mb-3">
                    <input class="form-check-input" type="checkbox" id="rememberMe" checked>
                    <label class="form-check-label mb-0 ms-3" for="rememberMe">Remember me</label>
                  </div>
                  <div class="text-center">
                    <!-- <button type="button" class="btn bg-gradient-dark w-100 my-4 mb-2">Sign in</button> -->
                    <input type="submit" class="btn bg-gradient-dark w-100 my-4 mb-2" value="Sign in">
                  </div>
                  <p class="mt-4 text-sm text-center">
                    Don't have an account?
                    <a href="{% url 'user:register' %}" class="text-primary text-gradient font-weight-bold">Sign up</a>
                  </p>  
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer position-absolute bottom-2 py-2 w-100">
        <div class="container">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col-12 col-md-6 my-auto">
              <div class="copyright text-center text-sm text-white text-lg-start">
                ©
                <script>
                  document.write(new Date().getFullYear())
                </script>,
                made with <i class="fa fa-heart" aria-hidden="true"></i> by
                <a href="https://www.creative-tim.com" class="font-weight-bold text-white" target="_blank">Creative
                  Tim</a>
                for a better web.
              </div>
            </div>
            <div class="col-12 col-md-6">
              <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                <li class="nav-item">
                  <a href="https://www.creative-tim.com" class="nav-link text-white" target="_blank">Creative Tim</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/presentation" class="nav-link text-white" target="_blank">About
                    Us</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/blog" class="nav-link text-white" target="_blank">Blog</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/license" class="nav-link pe-0 text-white"
                    target="_blank">License</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </main>
  <!--   Core JS Files   -->
  <script src="{% static 'js/core/popper.min.js' %}"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/plugins/chartjs.min.js' %}"></script>
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'js/material-dashboard.min.js' %}"></script>
</body>

</html>

WhatToDo/appuser/templates/sign-up.html
<!--
=========================================================
* Material Dashboard 3 - v3.2.0
=========================================================

* Product Page: https://www.creative-tim.com/product/material-dashboard
* Copyright 2024 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->

{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <title>
    Material Dashboard 3 by Creative Tim
  </title>
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700,900" />
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" />
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static 'css/material-dashboard.css' %}" rel="stylesheet" />
</head>

<body class="">
  
  <main class="main-content  mt-0">
    <section>
      <div class="page-header min-vh-100">
        <div class="container">
          <div class="row">
            <div
              class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 start-0 text-center justify-content-center flex-column">
              <div
                class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center"
                style="background-image: url({% static 'img/illustrations/illustration-signup.jpg'%}); background-size: cover;">
              </div>
            </div>
            <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-5">
              <div class="card card-plain">
                <div class="card-header">
                  <h4 class="font-weight-bolder">Sign Up</h4>
                  <p class="mb-0">Enter your email and password to register</p>
                </div>
                <div class="card-body">
                  <form role="form" method="post" action="{% url 'user:register' %}">
                    {% csrf_token %}
                    <div class="input-group input-group-outline mb-3">
                      <label class="form-label">Name</label>
                      <input type="text" class="form-control" name="username">
                    </div>
                    <div class="input-group input-group-outline mb-3">
                      <label class="form-label">Email</label>
                      <input type="email" class="form-control" name="email">
                    </div>
                    <div class="input-group input-group-outline mb-3">
                      <label class="form-label">Password</label>
                      <input type="password" class="form-control" name="password">
                    </div>
                    <div class="form-check form-check-info text-start ps-0">
                      <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" checked>
                      <label class="form-check-label" for="flexCheckDefault">
                        I agree the <a href="javascript:;" class="text-dark font-weight-bolder">Terms and Conditions</a>
                      </label>
                    </div>
                    <div class="text-center">
                      <!-- <button type="button" class="btn btn-lg bg-gradient-dark btn-lg w-100 mt-4 mb-0">Sign Up</button> -->
                      <input type="submit" class="btn btn-lg bg-gradient-dark btn-lg w-100 mt-4 mb-0" value="Sign Up">
                    </div>
                  </form>
                </div>
                <div class="card-footer text-center pt-0 px-lg-2 px-1">
                  <p class="mb-2 text-sm mx-auto">
                    Already have an account?
                    <a href="{% url 'user:login' %}" class="text-primary text-gradient font-weight-bold">Sign in</a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
  <!--   Core JS Files   -->

  <script src="{% static 'js/core/popper.min.js' %}"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/plugins/chartjs.min.js' %}"></script>
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'js/material-dashboard.min.js' %}"></script>
</body>

</html>